import { Conto } from "@/types";

export const MOCK_CONTOS: Conto[] = [
    {
        _id: "1",
        title: "O Papiro das Notificações Infinitas",
        slug: { current: "papiro-notificacoes-infinitas" },
        excerpt: "Glockenspiel encontra um papiro mágico que não para de vibrar e mostrar mensagens de taverneiros distantes.",
        content: [
            {
                _key: "block1",
                _type: "block",
                children: [{ _key: "c1", _type: "span", text: "Era uma manhã cinzenta na Taverna do Javali Saltitante quando Glockenspiel percebeu que seu papiro de mensagens estava agindo de forma estranha..." }],
                markDefs: [],
                style: "normal",
            },
        ],
        publishedAt: "2026-02-21T10:00:00Z",
        tags: ["Magia", "Humor", "Tecnologia Antiga"],
        readingTime: 5,
        featured: true,
        series: "Crônicas do Mundo Conectado",
    },
    {
        _id: "2",
        title: "A Greve dos Dragões de Entrega",
        slug: { current: "greve-dragoes-entrega" },
        excerpt: "Os dragões decidiram parar de entregar poções em 30 minutos, exigindo mais ovelhas por voo.",
        content: [],
        publishedAt: "2026-02-20T14:30:00Z",
        tags: ["Economia", "Dragões", "Sátira"],
        readingTime: 7,
        featured: false,
    },
    {
        _id: "3",
        title: "O Algoritmo de Cupido do Alquimista",
        slug: { current: "algoritmo-cupido-alquimista" },
        excerpt: "Uma poção de amor baseada em 'likes' e 'swipes' em espelhos mágicos causa caos no reino.",
        content: [],
        publishedAt: "2026-02-19T09:15:00Z",
        tags: ["Romance", "Alquimia", "Redes Sociais"],
        readingTime: 6,
        featured: true,
    },
    {
        _id: "4",
        title: "Cripto-Runas: O Golpe do Anão Mineiro",
        slug: { current: "cripto-runas-golpe-anao" },
        excerpt: "Venderam a Glockenspiel a ideia de investir em runas digitais que não ocupam espaço na bolsa.",
        content: [],
        publishedAt: "2026-02-18T20:00:00Z",
        tags: ["Dinheiro", "Anões", "Destaque"],
        readingTime: 8,
        featured: false,
    },
    {
        _id: "5",
        title: "O Home Office do Feiticeiro",
        slug: { current: "home-office-feiticeiro" },
        excerpt: "Tentar conjurar bolas de fogo via projeção astral enquanto os trasgos fazem barulho no andar de cima.",
        content: [],
        publishedAt: "2026-02-17T11:00:00Z",
        tags: ["Trabalho", "Feitiçaria", "Humor"],
        readingTime: 4,
        featured: false,
    },
    {
        _id: "6",
        title: "Influenciadores de Armadura: O Brilho da Távola",
        slug: { current: "influenciadores-armadura" },
        excerpt: "Cavaleiros que passam mais tempo polindo o escudo para o reflexo perfeito do que treinando com a espada.",
        content: [],
        publishedAt: "2026-02-16T16:00:00Z",
        tags: ["Moda", "Cavalaria", "Sátira"],
        readingTime: 9,
        featured: false,
    },
];
